import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { QueryProviders } from "@/providers/QueryProviders";
import { ThemeProvider } from "@mui/material";
import { theme } from "./styles/theme";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "700"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistMono.variable} antialiased overflow-hidden h-screen w-screen`}
      >
        <ToastContainer />
        <QueryProviders>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
